CREATE TABLE appointment_slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facility_id BIGINT NOT NULL REFERENCES facilities(id) ON DELETE CASCADE,
    starts_at TIMESTAMP WITH TIME ZONE NOT NULL,
    is_available BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE (facility_id, starts_at)
);

CREATE INDEX idx_appointment_slots_available
ON appointment_slots(facility_id, is_available, starts_at);

INSERT INTO appointment_slots (facility_id, starts_at)
SELECT id, TIMESTAMP WITH TIME ZONE '2026-07-28 10:00:00+08:00' FROM facilities;

INSERT INTO appointment_slots (facility_id, starts_at)
SELECT id, TIMESTAMP WITH TIME ZONE '2026-07-29 14:30:00+08:00' FROM facilities;

INSERT INTO appointment_slots (facility_id, starts_at)
SELECT id, TIMESTAMP WITH TIME ZONE '2026-07-30 11:00:00+08:00' FROM facilities;

